apiVersion: v1
kind: Service
metadata:
  name: result-service
  namespace: voting-app-ns
  labels:
    name: result-service
    app: demo-voting-app
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 32411
      targetPort: 80
  selector: 
    name: result-app-pod
    app: demo-voting-app
